### PR TITLE
As an admin I should be able to add clients, volunteers, donors to the database without creating user accounts for each. #16

### PR DESCRIPTION
**Pull request by nicholashu**
fixed staging conflicts, added feature.

### CODE REVIEW

**Comment by nicholashu** [comment]
Hold up, there seems to be an issue with the edit page now.

**Comment by nicholashu** [comment]
issues with merging fixed

**Comment by nicholashu** [comment]
I have an issue where if a new volunteer is created manually, it can't use the $update function in the controller as it is trying to do "PUT /admin/volunteers" instead of  /admin/volunteers/:volunteerId any ideas?

**Comment by DealPete** [comment]
That error suggests that the "_id" is blank for that user. Are you using a different id field for the manually added users?

**Comment by nicholashu** [comment]
It seems my objectId method of _id is flawed. I will have to create dummy users for manual additions.

**Pull request closed without merging**
